languages = Split("""
	Albanian
	Afrikaans
	Arabic
	Basque
	Belarusian
	Bosnian
	Breton
	Bulgarian
	Catalan
	Croatian
	Czech
	Danish
	Dutch
	English
	Esperanto
	Estonian
	Farsi
	Finnish
	French
	Galician
	German
	Greek
	Hebrew
	Hungarian
	Icelandic
	Indonesian
	Irish
	Italian
	Japanese
	Korean
	Kurdish
	Latvian
	Lithuanian
	Luxembourgish
	Macedonian
	Malay
	Mongolian
	Norwegian
	NorwegianNynorsk
	Polish
	Portuguese
	PortugueseBR
	Romanian
	Russian
	Serbian
	SerbianLatin
	SimpChinese
	Slovak
	Slovenian
	Spanish
	SpanishInternational
	Swedish
	Thai
	TradChinese
	Turkish
	Ukrainian
	Uzbek
	Welsh
""")

language_files = Flatten([(i + '.nlf', i + '.nsh') for i in languages])

Import('defenv')

defenv.DistributeContrib(language_files, path='Language files')
