target = 'nsExec'

files = Split("""
	nsexec.c
""")

libs = Split("""
	advapi32
	user32
	kernel32
""")

examples = Split("""
	test.nsi
""")

docs = Split("""
	nsExec.txt
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, examples, docs)

