target = 'InstallOptions'

files = Split("""
	InstallerOptions.cpp
""")

resources = Split("""
	ioptdll.rc
""")

libs = Split("""
	kernel32
	user32
	gdi32
	shell32
	comdlg32
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, res = resources)
