target = 'InstallOptions'

files = Split("""
	InstallerOptions.cpp
""")

resources = Split("""
	ioptdll.rc
""")

libs = Split("""
	kernel32
	user32
	gdi32
	shell32
	comdlg32
""")

Import('PluginEnv')

env = PluginEnv(target)

files += env.RES(resources)

plugin = env.SharedLibrary(target, files, LIBS = libs)

Return('plugin')
