target = 'AdvSplash'

files = Split("""
	AdvSplash.c
""")

libs = Split("""
	kernel32
	user32
	gdi32
	winmm
""")

examples = Split("""
	Example.nsi
""")

docs = Split("""
	advsplash.txt
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, examples, docs)
