target = "GenPat"

files = Split("""
	adler32.cpp
	Checksums.cpp
	ChunkedFile.cpp
	FileFormat1.cpp
	GlobalTypes.cpp
	main.cpp
	md5.c
	PatchGenerator.cpp
	POSIXUtil.cpp
""")

libs = Split("""
	z
""")

Import('BuildUtil')

BuildUtil(target, files, libs, flags = ['$EXCEPTION_FLAG','-std=c++11'], cross_platform = True, cli = True)
