target = 'StartMenu'

files = Split("""
	StartMenu.c
""")

resources = Split("""
	StartMenu.rc
""")

libs = Split("""
	kernel32
	user32
	gdi32
	shell32
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, res = resources, res_target = 'StartMenuRC')

