Import('env')

target = "substart"

files = Split("""
	substart.c
""")

libs = Split("""
""")

Import('BuildUtil')

substart = BuildUtil(target, files, libs, cli = True, noinstall = True)

env.DistributeBin(substart, names=['makensis.exe'], alias='install-compiler') # install as makensis
