examples = Split("""
	bigtest.nsi
	example1.nsi
	example2.nsi
	FileFunc.ini
	FileFunc.nsi
	FileFuncTest.nsi
	gfx.nsi
	languages.nsi
	Library.nsi
	LogicLib.nsi
	makensis.ini
	makensis.nsi
	Memento.nsi
	one-section.nsi
	primes.nsi
	rtest.nsi
	silent.nsi
	StrFunc.nsi
	TextFunc.ini
	TextFunc.nsi
	TextFuncTest.nsi
	UserVars.nsi
	VersionInfo.nsi
	viewhtml.nsi
	waplugin.nsi
	WordFunc.ini
	WordFunc.nsi
	WordFuncTest.nsi
""")

mui_examples = [
	'Modern UI/Basic.nsi',
	'Modern UI/HeaderBitmap.nsi',
	'Modern UI/InstallOptions.nsi',
	'Modern UI/MultiLanguage.nsi',
	'Modern UI/StartMenu.nsi',
	'Modern UI/WelcomeFinish.nsi',
	'Modern UI/ioA.ini',
	'Modern UI/ioB.ini',
	'Modern UI/ioC.ini'
]

Import('env')

env.DistributeExamples(examples)
env.DistributeExamples(mui_examples, path='Modern UI')
