target = 'Math'

if ['TEMP_MSVC2005']:
	files = Split("""
		Source/Math.c
		Source/MyMath.c
		Source/plugin.c
		Source/mathcrtmt.lib
	""")
else:
	files = Split("""
		Source/Math.c
		Source/MyMath.c
		Source/plugin.c
		Source/mathcrt.lib
	""")

libs = Split("""
	kernel32
""")

examples = Split("""
	math.nsi
	mathtest.nsi
	mathtest.ini
	mathtest.txt
""")

docs = Split("""
	Math.txt
""")

Import('BuildPlugin env')

BuildPlugin(target, files, libs, examples, docs, nodeflib = False, flags = ['$CPP_FLAG'])
