target = 'makensisw'

files = Split("""
	makensisw.cpp
	noclib.cpp
	toolbar.cpp
	utils.cpp
	version.cpp
""")

res = Split("""
	resource.rc
""")

resources = Split("""
	shell.ico
	makensisw.xml
	logo.bmp
	toolbar.bmp
	toolbar24.bmp
	toolbar24d.bmp
	toolbar24h.bmp
	#Contrib/Graphics/Icons/modern-install-blue-full.ico
""")

libs = Split("""
	kernel32
	advapi32
	user32
	gdi32
	shell32
	comdlg32
	comctl32
""")

Import('BuildUtil')

BuildUtil(
	target,
	files,
	libs,
	res = res,
	resources = resources,
	entry = 'WinMain',
	install = '',
	defines = ['WIN32_MEAN_AND_LEAN', 'RELEASE=2.0']
)
