examples = Split("""
	bigtest.nsi
	example1.nsi
	example2.nsi
	FileFunc.ini
	FileFunc.nsi
	FileFuncTest.nsi
	gfx.nsi
	AppGen.nsi
	install-per-user.nsi
	install-shared.nsi
	languages.nsi
	Library.nsi
	LogicLib.nsi
	makensis.nsi
	Memento.nsi
	NSISMenu.nsi
	one-section.nsi
	primes.nsi
	rtest.nsi
	silent.nsi
	StrFunc.nsi
	TextFunc.ini
	TextFunc.nsi
	TextFuncTest.nsi
	unicode.nsi
	VersionInfo.nsi
	waplugin.nsi
	WordFunc.ini
	WordFunc.nsi
	WordFuncTest.nsi
""")

mui_examples = [
	'Modern UI/Basic.nsi',
	'Modern UI/HeaderBitmap.nsi',
	'Modern UI/MultiLanguage.nsi',
	'Modern UI/StartMenu.nsi',
	'Modern UI/WelcomeFinish.nsi'
]

Import('env')

env.DistributeExamples(examples)
env.DistributeExamples(mui_examples, path='Modern UI')
