target = 'NSISdl'

files = Split("""
	asyncdns.cpp
	connection.cpp
	httpget.cpp
	nsisdl.cpp
	util.cpp
""")

libs = Split("""
	kernel32
	user32
	advapi32
	ws2_32
""")

Import('PluginEnv')

env = PluginEnv(target)

plugin = env.SharedLibrary(target, files, LIBS = libs)

Return('plugin')
