target = 'NSISdl'

files = Split("""
	asyncdns.cpp
	connection.cpp
	httpget.cpp
	nsisdl.cpp
	util.cpp
""")

libs = Split("""
	kernel32
	user32
	advapi32
	ws2_32
""")

docs = Split("""
	ReadMe.txt
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, docs = docs)
