target = 'Math'

files = Split("""
	Source/Math.c
	Source/MyMath.c
	Source/plugin.c
	Source/mathcrt.lib
""")

libs = Split("""
	kernel32
""")

Import('BuildPlugin env')

BuildPlugin(target, files, libs, nodeflib = 0, flags = env['CPP_FLAG'])
