target = 'Math'

files = Split("""
	Source/Math.c
	Source/MyMath.c
	Source/plugin.c
	Source/mathcrt.lib
""")

libs = Split("""
	kernel32
""")

Import('PluginEnv')

env = PluginEnv(target, entry = 'DllMain', nodeflib = 0)

env.Append(CPPFLAGS = env['CPP_FLAG'])

plugin = env.SharedLibrary(target, files, LIBS = libs)

Return('plugin')
