includes = Split("""
	Colors.nsh
	FileFunc.nsh
	Library.nsh
	LogicLib.nsh
	MUI.nsh
	Sections.nsh
	StrFunc.nsh
	TextFunc.nsh
	UpgradeDLL.nsh
	WinMessages.nsh
	WordFunc.nsh
""")

Import('env')

env.DistributeInclude(includes)
env.DistributeDocs('StrFunc.txt', path='StrFunc')
