target = 'UserInfo'

files = Split("""
	UserInfo.c
""")

libs = Split("""
	kernel32
	advapi32
""")

Import('PluginEnv')

env = PluginEnv(target)

plugin = env.SharedLibrary(target, files, LIBS = libs)

Return('plugin')
