target = 'Splash'

files = Split("""
	splash.c
""")

libs = Split("""
	kernel32
	user32
	gdi32
	winmm
""")

examples = Split("""
	Example.nsi
""")

docs = Split("""
	splash.txt
""")

Import('BuildPlugin')

BuildPlugin(target, files, libs, examples, docs)
