includes = Split("""
	Colors.nsh
	FileFunc.nsh
	Integration.nsh
	LangFile.nsh
	Library.nsh
	LogicLib.nsh
	Memento.nsh
    ModernXL.nsh
    ModernXXL.nsh
	MUI.nsh
	MUI2.nsh
	Sections.nsh
	StrFunc.nsh
	TextFunc.nsh
	UpgradeDLL.nsh
	Util.nsh
	VB6RunTime.nsh
	WinCore.nsh
	WinMessages.nsh
	WinVer.nsh
	WordFunc.nsh
	x64.nsh
""")

includesWin = Split("""
	Win/COM.nsh
	Win/Propkey.nsh
	Win/WinDef.nsh
	Win/WinError.nsh
	Win/WinNT.nsh
	Win/WinUser.nsh
""")

Import('env')

env.DistributeInclude(includes)
env.DistributeInclude(includesWin, path='Win')
env.DistributeDocs('StrFunc.txt', path='StrFunc')
