target = 'makensisw'

files = Split("""
	makensisw.cpp
	toolbar.cpp
	utils.cpp
	version.cpp
	update.cpp
""")

res = Split("""
	resource.rc
""")

resources = Split("""
	icon.ico
	assoc_nsi.ico
	assoc_nsh.ico
	makensisw.xml
	logo.bmp
	toolbar.bmp
	toolbar24.bmp
	toolbar24d.bmp
	toolbar24h.bmp
""")

libs = Split("""
	kernel32
	advapi32
	user32
	gdi32
	shell32
	shlwapi
	comdlg32
	comctl32
	wininet
""")

docs = Split("""
	License.txt
	Readme.txt
""")

Import('BuildUtil')

BuildUtil(
	target,
	files,
	libs,
	res = res,
	resources = resources,
	entry = None,
	defines = ['RELEASE=2.3.3'],
	docs = docs,
	root_util = True
)
